version: "3.6"

networks:
  default:
    external:
      name: docker-dev

volumes:
  pkg:
  db-volume:

services:

  capricorn_example:
    image: app:local
    command: ./capricorn_example server
    depends_on:
      - db_capricorn_example
    volumes:
      - pkg:/go/pkg
      - .:/capricorn-example
    working_dir: /capricorn-example/src
    ports:
      - "80"
    env_file:
      - .app.env
    environment:
      VIRTUAL_HOST: capricorn-example.local
      ENV: local
      HTTP_PORT: 80
      MIGRATION_PATH: /capricorn-example/src/db
    networks:
      default:
        aliases:
          - capricorn-example.local

  db_capricorn_example:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: capricorn_example
    ports:
      - "${HOST_DB_PORT:-3310}:3306"
    volumes:
      - db-volume:/var/lib/mysql
