// Code generated by "capricorn"; DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"
)

var Example = &cobra.Command{
	Use:   "example",
	Short: "",
	Run:   func(cmd *cobra.Command, args []string) {},
}
