// Code generated by "capricorn"; DO NOT EDIT.
package cmd

import (
	// imported for auto migration registration
	_ "github.com/68696c6c/capricorn-example/db/migrations"

	"github.com/68696c6c/goat"
	"github.com/pkg/errors"
	"github.com/pressly/goose"
	"github.com/spf13/cobra"
)

var Migrate = &cobra.Command{
	Use:   "migrate [OPTIONS] COMMAND",
	Short: "Root migration command.",
	Example: `migrate status
migrate create init sql
migrate create add_some_column sql
migrate create fetch_user_data go
migrate up`,
	Run: func(cmd *cobra.Command, args []string) {
		goat.Init()

		db, err := goat.GetMainDB()
		if err != nil {
			goat.ExitError(errors.Wrap(err, "error initializing migration connection"))
		}

		err = goose.SetDialect("mysql")
		if err != nil {
			goat.ExitError(errors.Wrap(err, "error initializing goose"))
		}

		var arguments []string
		if len(args) > 1 {
			arguments = args[1:]
		}

		err = goose.Run(args[0], db.DB(), ".", arguments...)
		if err != nil {
			goat.ExitError(err)
		}

		goat.ExitSuccess()
	},
}
