// Code generated by "capricorn"; DO NOT EDIT.
package cmd

import (
	"github.com/68696c6c/capricorn-example/app"
	"github.com/68696c6c/capricorn-example/http"

	"github.com/68696c6c/goat"
	"github.com/pkg/errors"
	"github.com/spf13/cobra"
)

var Server = &cobra.Command{
	Use:   "server",
	Short: "Runs the Capricorn Example web server",
	Run: func(cmd *cobra.Command, args []string) {
		goat.Init()

		logger := goat.GetLogger()

		db, err := goat.GetMainDB()
		if err != nil {
			goat.ExitError(errors.Wrap(err, "failed to initialize database connection"))
		}

		services, err := app.GetApp(db, logger)
		if err != nil {
			goat.ExitError(errors.Wrap(err, "failed to initialize application services"))
		}

		r := http.InitRouter(services)
		r.Run()
	},
}
