// Code generated by "capricorn"; DO NOT EDIT.
package http

import (
	"github.com/68696c6c/capricorn-example/app"
	"github.com/68696c6c/capricorn-example/app/handlers"

	"github.com/68696c6c/goat"
	"github.com/gin-gonic/gin"
)

func InitRouter(s app.ServiceContainer) goat.Router {
	router := goat.GetRouter()
	engine := router.GetEngine()

	engine.GET("/health", func(c *gin.Context) {
		goat.RespondMessage(c, "ok")
	})
	engine.GET("/version", func(c *gin.Context) {
		// TODO: show version.
		goat.RespondMessage(c, "something helpful here")
	})
	api := engine.Group("/api")

	{
		g := api.Group("/users")
		g.POST("", goat.BindMiddleware(handlers.CreateUserRequest{}), handlers.CreateUser(s.Errors, s.UsersRepo))
		g.GET("/:%s", handlers.ViewUser(s.Errors, s.UsersRepo))
		g.GET("", handlers.ListUsers(s.Errors, s.UsersRepo))
		g.PUT("/:id", goat.BindMiddleware(handlers.UpdateUserRequest{}), handlers.UpdateUser(s.Errors, s.UsersRepo))
		g.DELETE("/:id", handlers.DeleteUser(s.Errors, s.UsersRepo))
	}
	{
		g := api.Group("/organizations")
		g.POST("", goat.BindMiddleware(handlers.CreateOrganizationRequest{}), handlers.CreateOrganization(s.Errors, s.OrganizationsRepo))
		g.GET("/:%s", handlers.ViewOrganization(s.Errors, s.OrganizationsRepo))
		g.GET("", handlers.ListOrganizations(s.Errors, s.OrganizationsRepo))
		g.PUT("/:id", goat.BindMiddleware(handlers.UpdateOrganizationRequest{}), handlers.UpdateOrganization(s.Errors, s.OrganizationsRepo))
		g.DELETE("/:id", handlers.DeleteOrganization(s.Errors, s.OrganizationsRepo))
	}

	return router
}
