// Code generated by "capricorn"; DO NOT EDIT.
package app

import (
	"github.com/68696c6c/capricorn-example/app/repos"

	"github.com/68696c6c/goat"
	"github.com/jinzhu/gorm"
	"github.com/sirupsen/logrus"
)

var container ServiceContainer

type ServiceContainer struct {
	DB                *gorm.DB
	Logger            *logrus.Logger
	Errors            goat.ErrorHandler
	OrganizationsRepo repos.OrganizationsRepo
	UsersRepo         repos.UsersRepo
}

func GetApp(dbConnection *gorm.DB, logger *logrus.Logger) (ServiceContainer, error) {
	if container != (ServiceContainer{}) {
		return container, nil
	}

	container = ServiceContainer{
		DB:                dbConnection,
		Logger:            logger,
		Errors:            goat.NewErrorHandler(logger),
		OrganizationsRepo: repos.NewOrganizationsRepo(dbConnection),
		UsersRepo:         repos.NewUsersRepo(dbConnection),
	}

	return container, nil
}
