// Code generated by "stringer -type=UserType -trimprefix=UserType"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserTypeUser-1]
	_ = x[UserTypeAdmin-2]
	_ = x[UserTypeSuper-3]
}

const _UserType_name = "UserAdminSuper"

var _UserType_index = [...]uint8{0, 4, 9, 14}

func (i UserType) String() string {
	i -= 1
	if i < 0 || i >= UserType(len(_UserType_index)-1) {
		return "UserType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UserType_name[_UserType_index[i]:_UserType_index[i+1]]
}
