// Code generated by "capricorn"; DO NOT EDIT.
package main

import (
	"os"
	"strings"

	"github.com/68696c6c/capricorn-example/cmd"

	_ "github.com/go-sql-driver/mysql"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func main() {
	viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	viper.AutomaticEnv()
	viper.SetDefault("author", "Aaron Hill <68696c6c@gmail.com>")
	viper.SetDefault("license", "none")

	rootCmd := &cobra.Command{
		Use:   "app",
		Short: "Root command for Capricorn Example",
	}

	rootCmd.SetOut(os.Stdout)
	rootCmd.AddCommand(
		cmd.Server,
		cmd.Migrate,
		cmd.Example,
	)

	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}
